language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.5.6 on Xenial Linux"
      python: 3.5           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.5
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install -r requirements.txt
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: 
  python3 bigo_calc.py examples/ForTest.c || python bigo_calc.py examples/ForTest.c
